### ISSUE TITLE
Receiving error for outdated mod version incorrectly.

### ISSUE THREAD

**Issue by SodiumShine** [dantaeusb-mc/ZetterGallery#1]
![image](https://user-images.githubusercontent.com/4461697/174591843-6062c36e-00ed-4511-a688-da4c376c3009.png)
When attempting to interact with a painting merchant the above error message is received despite the mod being on the latest version.

The mod version I have is zettergallery-0.2.1-1.18.2-beta.jar. 
Zetter version is zetter-0.14.3-1.18.2-beta.jar

Forge version is 40.1.48

**Comment by dantaeusb** [comment]
Hi, service is just launched and a bit wacky sometimes, sorry, just fixed that. No update on your side needed. 

You might need to re-register your server by exiting the world and getting back in (or restarting the server if it's dedicated).
