### ISSUE TITLE
[Suggestion] Painted canvas items should show what's on them

### ISSUE THREAD

**Issue by scribe-of-days** [dantaeusb-mc/ZetterGallery#19]
Currently the painted canvases all look the same until you put them into the artist table. I'm working on creating a 2x4 painting which requires that I break down the project into smaller constituent parts and then merge them. Trying to figure out what piece goes where and having to guess which is which is a little bit frustrating so it'd be nice if once they were painted on, it showed what was on them--just a thought. Thanks :)

**Comment by dantaeusb** [comment]
Moved here: https://github.com/dantaeusb-mc/Zetter/issues/94. It's partially ready (that's why Canvas looks a bit weird in hands), but I had to disable this feature when migrating from 1.18 to 1.19. Hope to return to it soon and finally implement that feature.

**Comment by dantaeusb** [comment]
Closing here, as it's core mod feature mentioned above. Track status in https://github.com/dantaeusb-mc/Zetter/issues/94
